spring.application.name=usp_gym

spring.datasource.url=jdbc:postgresql://localhost:5432/FitnesBase
spring.datasource.username=fitnesadmin
spring.datasource.password=uspadmin
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.address=0.0.0.0
server.port=8080